### ISSUE TITLE
There is a plan to export modelStudio to python?

### ISSUE THREAD

**Issue by set92** [ModelOriented/dime#100]
I'm trying to create an automatic pipeline in which I get the data from bigquery, process it with pycaret/autogluon to create a model, and I was searching for a tool for XAI. I really like the design and the easiness of using it, but I don't think that creating a pkl file, installing and running R only to generate this part is the best thing. And moving all the development to R is not really an option.

So, my question was if there is some plan to have model studio in python or it has too many dependencies in R to be feasible?

**Comment by hbaniecki** [comment]
Hi @set92, there are no plans to make a `modelStudio` Python package.
We developed an XAI dashboard for Python called Arena in the `dalex` package: 
- demo https://arena.drwhy.ai/?demo=2
- dalex https://dalex.drwhy.ai/python
- Arena documentation https://arena.drwhy.ai/docs/guide/basic-concepts/
- dalex code example https://dalex.drwhy.ai/python-dalex-arena.html

It is more advanced than `modelStudio` but might suit your needs.

**Comment by set92** [comment]
I was trying Arena, but I thought it was less useful since it seemed more for BI instead of having it at the end of a pipeline, but well knowing that I'll compare both of those approaches tomorrow and see which is the better option. Thanks :D
