### ISSUE TITLE
Is 4x4 panels the only way to present ModelStudio?

### ISSUE THREAD

**Issue by CoolShades** [ModelOriented/dime#115]
just a half scroll down from https://modelstudio.drwhy.ai/, we are greeted by a very nice 1x2 panel modelStudio.

All variations of modelStudio I am able to create are only 4x4 panels. I can't see any option/argument to choose the sleeker version of modelStudio. 

CLOSED: as there is a troubleshooting section.

**Comment by CoolShades** [comment]
CLOSED: as there is a troubleshooting section.

**Comment by hbaniecki** [comment]
[ answered in [https://github.com/ModelOriented/modelStudio/issues/54#issuecomment-1537548672](https://github.com/ModelOriented/modelStudio/issues/54#issuecomment-1537548672) ]
