### ISSUE TITLE
Missing parts in documentation

### ISSUE THREAD

**Issue by expectopatronum** [ModelOriented/dime#28]
Hi, I am one of the [reviewers for your JOSS submission](https://github.com/openjournals/joss-reviews/issues/1798). I thought I'd put the things I miss in the documentation and the corresponding review checklist items here:
* **A statement of need:** It is described what the software should solve, but I somehow miss what the target audience is. Is it researcher, machine learning practitioners, anyone interested in interpretable machine learning...?
* **Installation instructions:** (this might be because I haven't used R much in the past year - as stated before I started the review). When I installed your package (on a Manjaro machine), I had issues because it also installed `glmnet` for which it requires `gcc-fortran` (which I had to install using my package manager). First I am wondering why it knew that it had to install glmnet - it is not mentioned in this libraries DESCRIPTION (I assume it is a dependency of one of the other packages?) And I am also not sure if it is required that your README mentions that one might need to install `gcc-fortran` (because it is not directly used by your package). Just wanted to let you know that this might be an issue :)
* **Automated tests:** The reviewing check list asks "Are there automated tests or manual steps described so that the functionality of the software can be verified?" I can't find such a thing, maybe you can point me to it.
*  **Community guidelines:** The reviewing check list asks "Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support" I can't find such a thing, maybe you can point me to it.

**Comment by hbaniecki** [comment]
Hi, I am glad to see this checklist! Here are some notes:

1.  I think that there is no specific target for this package (so basicaly anyone interested in explaining their model). The `modelStudio` package is a part of the [DrWhy.AI](https://github.com/ModelOriented/DrWhy/blob/master/README.md) universe (it is stated in `README.md`) and more information can be found there.
2. This package is on CRAN. Installation should be easy and instructions are clear (in `README.md`). It automatically installs dependencies (other R packages that are stated in Depends/Imports in the `DESCRIPTION` file with all of their dependencies and so on). The `glmnet` package is an import for `ingredients` package (very heavy though). I will try to remove it from Imports in the `ingredients` package. `glmnet` usage is in development stage and it is not needed for the `modelStudio` package.
3. This package has a 99% test coverage and all of the tests are automated. They can be found in `tests` folder. Continuous integration is made possible by [Travis CI](https://travis-ci.org/). Basically it will test code on every commit/pull request on this repository. This package is also tested by CRAN and complies with their (for some people strict) policies. Results of this checks (for different OS) can be found [here](https://cran.r-project.org/web/checks/check_results_modelStudio.html). 
4.  Sure, I will add `CONTRIBUTING.md` file to the repo.

I remain at your disposal for any further questions :smile:

**Comment by expectopatronum** [comment]
Thanks, this resolves my questions/concerns!
