### ISSUE TITLE
problem in describe

### ISSUE THREAD

**Issue by AleksandraGro** [ModelOriented/dime#34]
breakpoint_description <- ifelse(multiple_breakpoints, paste0("Breakpoints are identified at (", 
+     variables, " = ", cut_name, " and ", variables, " = ", 
+     round(df[cutpoint_additional, variables], 3), ")."), 
+     paste0("Breakpoint is identified at (", variables, " = ", 
+       cut_name, ")."))
Browse[2]> prefix <- paste0("The highest prediction occurs for (", 
+     variables, " = ", max_name, "),", " while the lowest for (", 
+     variables, " = ", min_name, ").\n", breakpoint_description)
Browse[2]> cutpoint <- ifelse(multiple_breakpoints, cutpoint_additional, 
+     cutpoint)
Browse[2]> sufix <- describe_numeric_variable(original_x = attr(x, 
+     "observations"), df = df, cutpoint = cutpoint, variables = variables)
Browse[2]> description <- paste(introduction, prefix, sufix, sep = "\n\n")
Browse[2]> description

**Comment by pbiecek** [comment]
fixed in https://github.com/ModelOriented/ingredients/issues/76
