### ISSUE TITLE
new plot: Target Average vs Feature [EDA]

### ISSUE THREAD

**Issue by hbaniecki** [ModelOriented/dime#41]

**Comment by MLud** [comment]
and average prediction/score from model

**Comment by hbaniecki** [comment]
Hi @MLud!
Average prediction is an intercept line in both BreakDown and SHAP plots. New version of this package should be on master branch tomorrow (works with the new version of ingredients package) and later on CRAN. Feel free to send more feedback.

**Comment by MLud** [comment]
I thought that we are talking about EDA box. It is very interesting what is the average target and score in each piece of variable.
