### ISSUE TITLE
Display feature of interest in plots

### ISSUE THREAD

**Issue by andreassot10** [ModelOriented/dime#70]
Hi,

I would like to know how to display the features of interest on a `modelStudio` plot. It looks like `modelStudio` chooses the first feature in the data frame by default and that information on the rest of features is only made available by hovering over the plots.

Example from `modelStudio` [website](https://modelstudio.drwhy.ai/):

```
library("DALEX")
library("modelStudio")

# fit a model
model <- glm(survived ~., data = titanic_imputed, family = "binomial")

# create an explainer for the model    
explainer <- explain(model,
                     data = titanic_imputed,
                     y = titanic_imputed$survived,
                     label = "Titanic GLM")

# make a studio for the model
modelStudio(explainer)
```
The only feature displayed on the plot is `gender`, which is the first column in `titanic_imputed`.

Unless I'm missing something, it appears that there is no mention in the [manual ](https://cran.r-project.org/web/packages/modelStudio/modelStudio.pdf)about how to change this. There's also no option for changing this in the actual plot.

Thanks.

**Comment by hbaniecki** [comment]
Hi,
This can be done by clicking on the bars (e.g. Break Down, Feature Importance). I will add it to the manual. 
Probably should consider adding another dropdown for variable choice too.

**Comment by andreassot10** [comment]
> 
> 
> Hi,
> This can be done by clicking on the bars (e.g. Break Down, Feature Importance). I will add it to the manual.
> Probably should consider adding another dropdown for variable choice too.

Break Down & Feature Importance bars probably the only places on the visualization I didn't click on! Mention in the manual as well as a drop-down for feature choice in the plot would definitely help.
Many thanks

**Comment by hbaniecki** [comment]
Testing a new dropdown for variables on the master branch 867e12a. It will happen in the next CRAN release (v1.2.0).

**Comment by andreassot10** [comment]
Fab, thanks
